//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SterlingBankLMS.Web.Areas.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string CommentMessage { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int LessonId { get; set; }
        public bool Flagged { get; set; }
        public int Status { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
